name: Build All

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Build with msbuild
      run: msbuild Facepunch.Steamworks\Facepunch.Steamworks.Win64.csproj
